# GTB DLP Policy: Sensitive Data Detection
# Detects and blocks common sensitive data patterns (PII, financial, credentials)
# Author: Manjula Wickramasuriya
# Repo: https://github.com/Manjula101/gtb-dlp-policies

policy_name: "Sensitive Data Detection"
description: "Blocks transmission of sensitive information such as credit cards, SSNs, passwords, and API keys"
severity: "High"
enabled: true

# Trigger conditions
triggers:
  - type: "content_scan"
    patterns:
      - name: "Credit Card"
        regex: "(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11})"
        action: "block"
      
      - name: "SSN / National ID"
        regex: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
        action: "block"

      - name: "Password / Credential"
        regex: "(?i)(password|pwd|pass|secret|key|token)\\s*[=:]\\s*\\S+"
        action: "block"

      - name: "API Key"
        regex: "(?i)(api_key|apikey|secret_key|auth_token)\\s*[=:]\\s*[A-Za-z0-9_-]{20,}"
        action: "block"

# Actions when triggered
actions:
  - type: "block"
    message: "Sensitive data detected. Transfer blocked for security compliance."
  - type: "log"
    level: "high"
  - type: "notify"
    recipients: ["security-team@gttb.com"]   # Change to your team email

# Scope
scope:
  - direction: ["outbound", "internal"]
  - channels: ["email", "web", "usb", "cloud_storage"]

# Exceptions (optional)
exceptions:
  - name: "Approved Finance Team"
    condition: "user.group == 'finance' AND destination == 'internal.finance.system'"
